USE Prueba;

-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2022-12-06 17:37:18 CST
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE Estados 
    (
     id_estado INTEGER NOT NULL , 
     estado VARCHAR (40) 
    )
GO

ALTER TABLE Estados ADD CONSTRAINT Estados_PK PRIMARY KEY CLUSTERED (id_estado)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE REG_AUTO 
    (
     id_auto INTEGER NOT NULL , 
     marca VARCHAR (100) , 
     color VARCHAR (50) , 
     modelo VARCHAR (10) , 
     precio DECIMAL (10,2) , 
     fecha_recepcion DATE , 
     id_estado INTEGER NOT NULL 
    )
GO

ALTER TABLE REG_AUTO ADD CONSTRAINT REG_AUTO_PK PRIMARY KEY CLUSTERED (id_auto)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE REG_AUTO 
    ADD CONSTRAINT REG_AUTO_Estados_FK FOREIGN KEY 
    ( 
     id_estado
    ) 
    REFERENCES Estados 
    ( 
     id_estado 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             2
-- CREATE INDEX                             0
-- ALTER TABLE                              3
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
